services:

  postgres-container:
    image: postgres:17
    container_name: postgres-container
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_rest_db

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data


  node-container:
    build: .

    container_name: node-container

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NODE_ENV: development
      PORT: 3000

    depends_on:
      - postgres-container

    command: npm run dev


  nginx-container:
    image: nginx:latest

    container_name: nginx-container

    ports:
      - "8080:80"

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - node-container


volumes:
  pgdata: