-- Dados de teste - minimo 100 registros

-- Users (10 registros)
INSERT INTO users (name, email, password, "createdAt", "updatedAt") VALUES
('Admin Sistema',   'admin@escola.com',    '$2b$10$hash_admin',    NOW(), NOW()),
('Gabriel Souza',   'gabriel@escola.com',  '$2b$10$hash_gabriel',  NOW(), NOW()),
('Mariana Lima',    'mariana@escola.com',  '$2b$10$hash_mariana',  NOW(), NOW()),
('Rafael Costa',    'rafael@escola.com',   '$2b$10$hash_rafael',   NOW(), NOW()),
('Beatriz Alves',   'beatriz@escola.com',  '$2b$10$hash_beatriz',  NOW(), NOW()),
('Lucas Pereira',   'lucas@escola.com',    '$2b$10$hash_lucas',    NOW(), NOW()),
('Fernanda Rocha',  'fernanda@escola.com', '$2b$10$hash_fernanda', NOW(), NOW()),
('Thiago Martins',  'thiago@escola.com',   '$2b$10$hash_thiago',   NOW(), NOW()),
('Camila Ferreira', 'camila@escola.com',   '$2b$10$hash_camila',   NOW(), NOW()),
('Pedro Carvalho',  'pedro@escola.com',    '$2b$10$hash_pedro',    NOW(), NOW());

-- Courses (20 registros)
INSERT INTO courses (title, description, "createdAt", "updatedAt") VALUES
('Node.js Avancado',        'APIs REST, JWT e middlewares.',         NOW(), NOW()),
('PostgreSQL para Devs',    'Modelagem relacional e queries.',       NOW(), NOW()),
('Docker e Containers',     'Imagens, volumes e redes.',             NOW(), NOW()),
('React do Zero',           'Componentes, hooks e estado.',          NOW(), NOW()),
('TypeScript Essencial',    'Tipagem estatica e interfaces.',        NOW(), NOW()),
('Python para Dados',       'Pandas, NumPy e visualizacao.',         NOW(), NOW()),
('Seguranca Web',           'OWASP Top 10 e autenticacao.',          NOW(), NOW()),
('AWS Cloud Practitioner',  'Servicos AWS, IAM, EC2 e S3.',         NOW(), NOW()),
('Git e GitHub Avancado',   'Branching, rebase e CI/CD.',            NOW(), NOW()),
('Clean Code',              'Principios SOLID e refatoracao.',       NOW(), NOW()),
('MongoDB e NoSQL',         'Documentos, colecoes e agregacoes.',    NOW(), NOW()),
('Linux para Devs',         'Shell script e gerenciamento.',         NOW(), NOW()),
('GraphQL na Pratica',      'Queries, mutations e resolvers.',       NOW(), NOW()),
('Testes Automatizados',    'Jest, TDD e cobertura.',                NOW(), NOW()),
('Kubernetes Fundamentos',  'Pods, deployments e services.',         NOW(), NOW()),
('Vue.js 3',                'Composition API e Pinia.',              NOW(), NOW()),
('Java Spring Boot',        'REST APIs e JPA.',                      NOW(), NOW()),
('DevOps na Pratica',       'CI/CD e monitoramento.',                NOW(), NOW()),
('Redis e Cache',           'Estruturas de dados e sessoes.',        NOW(), NOW()),
('Arquitetura de Software', 'Microsservicos e DDD.',                 NOW(), NOW());

-- Students (50 registros)
INSERT INTO students (name, email, "createdAt", "updatedAt") VALUES
('Ana Paula Silva',      'ana.silva@aluno.com',       NOW(), NOW()),
('Bruno Oliveira',       'bruno.oliveira@aluno.com',  NOW(), NOW()),
('Carla Mendes',         'carla.mendes@aluno.com',    NOW(), NOW()),
('Diego Santos',         'diego.santos@aluno.com',    NOW(), NOW()),
('Elisa Fernandes',      'elisa.fernandes@aluno.com', NOW(), NOW()),
('Felipe Gomes',         'felipe.gomes@aluno.com',    NOW(), NOW()),
('Gabriela Nunes',       'gabriela.nunes@aluno.com',  NOW(), NOW()),
('Henrique Barbosa',     'henrique.barbosa@aluno.com',NOW(), NOW()),
('Isabela Castro',       'isabela.castro@aluno.com',  NOW(), NOW()),
('Joao Victor Reis',     'joao.reis@aluno.com',       NOW(), NOW()),
('Karen Lima',           'karen.lima@aluno.com',      NOW(), NOW()),
('Leonardo Azevedo',     'leonardo.azevedo@aluno.com',NOW(), NOW()),
('Mariana Costa',        'mariana.costa@aluno.com',   NOW(), NOW()),
('Nicolas Rodrigues',    'nicolas.rodrigues@aluno.com',NOW(),NOW()),
('Olivia Teixeira',      'olivia.teixeira@aluno.com', NOW(), NOW()),
('Paulo Moura',          'paulo.moura@aluno.com',     NOW(), NOW()),
('Quezia Albuquerque',   'quezia.albu@aluno.com',     NOW(), NOW()),
('Roberto Freitas',      'roberto.freitas@aluno.com', NOW(), NOW()),
('Sabrina Vieira',       'sabrina.vieira@aluno.com',  NOW(), NOW()),
('Tiago Nascimento',     'tiago.nasc@aluno.com',      NOW(), NOW()),
('Ursula Fonseca',       'ursula.fonseca@aluno.com',  NOW(), NOW()),
('Vinicius Cardoso',     'vinicius.cardoso@aluno.com',NOW(), NOW()),
('Wanderson Pinto',      'wanderson.pinto@aluno.com', NOW(), NOW()),
('Xenya Borges',         'xenya.borges@aluno.com',    NOW(), NOW()),
('Yasmin Cavalcante',    'yasmin.cav@aluno.com',      NOW(), NOW()),
('Zaqueu Monteiro',      'zaqueu.mont@aluno.com',     NOW(), NOW()),
('Alice Ramos',          'alice.ramos@aluno.com',     NOW(), NOW()),
('Bernardo Lopes',       'bernardo.lopes@aluno.com',  NOW(), NOW()),
('Cecilia Pires',        'cecilia.pires@aluno.com',   NOW(), NOW()),
('Danilo Correia',       'danilo.correia@aluno.com',  NOW(), NOW()),
('Emanuela Duarte',      'emanuela.duarte@aluno.com', NOW(), NOW()),
('Fabricio Melo',        'fabricio.melo@aluno.com',   NOW(), NOW()),
('Giovanna Campos',      'giovanna.campos@aluno.com', NOW(), NOW()),
('Hiago Tavares',        'hiago.tavares@aluno.com',   NOW(), NOW()),
('Iris Cunha',           'iris.cunha@aluno.com',      NOW(), NOW()),
('Jadson Ribeiro',       'jadson.ribeiro@aluno.com',  NOW(), NOW()),
('Keila Sousa',          'keila.sousa@aluno.com',     NOW(), NOW()),
('Lorena Macedo',        'lorena.macedo@aluno.com',   NOW(), NOW()),
('Matheus Esteves',      'matheus.esteves@aluno.com', NOW(), NOW()),
('Natalia Queiroz',      'natalia.queiroz@aluno.com', NOW(), NOW()),
('Octavio Leite',        'octavio.leite@aluno.com',   NOW(), NOW()),
('Patricia Brito',       'patricia.brito@aluno.com',  NOW(), NOW()),
('Quintino Andrade',     'quintino.andrade@aluno.com',NOW(), NOW()),
('Renata Dias',          'renata.dias@aluno.com',     NOW(), NOW()),
('Samuel Araujo',        'samuel.araujo@aluno.com',   NOW(), NOW()),
('Tatiane Vasconcelos',  'tatiane.vasc@aluno.com',    NOW(), NOW()),
('Ubirajara Matos',      'ubira.matos@aluno.com',     NOW(), NOW()),
('Valeria Nogueira',     'valeria.nogueira@aluno.com',NOW(), NOW()),
('Wellington Cruz',      'wellington.cruz@aluno.com', NOW(), NOW()),
('Xuxa Pimentel',        'xuxa.pimentel@aluno.com',   NOW(), NOW());

-- Matriculas student_courses (140+ registros)
INSERT INTO student_courses (student_id, course_id, "createdAt", "updatedAt") VALUES
(1,1,NOW(),NOW()),(1,3,NOW(),NOW()),(1,9,NOW(),NOW()),
(2,1,NOW(),NOW()),(2,2,NOW(),NOW()),(2,14,NOW(),NOW()),
(3,4,NOW(),NOW()),(3,5,NOW(),NOW()),(3,13,NOW(),NOW()),
(4,3,NOW(),NOW()),(4,8,NOW(),NOW()),(4,18,NOW(),NOW()),
(5,1,NOW(),NOW()),(5,6,NOW(),NOW()),(5,10,NOW(),NOW()),
(6,2,NOW(),NOW()),(6,7,NOW(),NOW()),(6,14,NOW(),NOW()),
(7,4,NOW(),NOW()),(7,16,NOW(),NOW()),(7,20,NOW(),NOW()),
(8,1,NOW(),NOW()),(8,3,NOW(),NOW()),(8,15,NOW(),NOW()),
(9,5,NOW(),NOW()),(9,9,NOW(),NOW()),(9,11,NOW(),NOW()),
(10,2,NOW(),NOW()),(10,7,NOW(),NOW()),(10,19,NOW(),NOW()),
(11,1,NOW(),NOW()),(11,4,NOW(),NOW()),(11,8,NOW(),NOW()),
(12,3,NOW(),NOW()),(12,6,NOW(),NOW()),(12,12,NOW(),NOW()),
(13,2,NOW(),NOW()),(13,5,NOW(),NOW()),(13,17,NOW(),NOW()),
(14,1,NOW(),NOW()),(14,10,NOW(),NOW()),(14,14,NOW(),NOW()),
(15,4,NOW(),NOW()),(15,7,NOW(),NOW()),(15,13,NOW(),NOW()),
(16,3,NOW(),NOW()),(16,8,NOW(),NOW()),(16,20,NOW(),NOW()),
(17,1,NOW(),NOW()),(17,6,NOW(),NOW()),(17,11,NOW(),NOW()),
(18,2,NOW(),NOW()),(18,9,NOW(),NOW()),(18,15,NOW(),NOW()),
(19,5,NOW(),NOW()),(19,10,NOW(),NOW()),(19,18,NOW(),NOW()),
(20,1,NOW(),NOW()),(20,3,NOW(),NOW()),(20,7,NOW(),NOW()),
(21,4,NOW(),NOW()),(21,12,NOW(),NOW()),(21,16,NOW(),NOW()),
(22,2,NOW(),NOW()),(22,6,NOW(),NOW()),(22,19,NOW(),NOW()),
(23,1,NOW(),NOW()),(23,8,NOW(),NOW()),(23,14,NOW(),NOW()),
(24,3,NOW(),NOW()),(24,5,NOW(),NOW()),(24,11,NOW(),NOW()),
(25,7,NOW(),NOW()),(25,9,NOW(),NOW()),(25,17,NOW(),NOW()),
(26,1,NOW(),NOW()),(26,2,NOW(),NOW()),(26,4,NOW(),NOW()),(26,10,NOW(),NOW()),
(27,3,NOW(),NOW()),(27,6,NOW(),NOW()),(27,13,NOW(),NOW()),
(28,5,NOW(),NOW()),(28,8,NOW(),NOW()),(28,20,NOW(),NOW()),
(29,1,NOW(),NOW()),(29,7,NOW(),NOW()),(29,15,NOW(),NOW()),
(30,2,NOW(),NOW()),(30,9,NOW(),NOW()),(30,12,NOW(),NOW()),
(31,4,NOW(),NOW()),(31,6,NOW(),NOW()),(31,18,NOW(),NOW()),
(32,1,NOW(),NOW()),(32,3,NOW(),NOW()),(32,11,NOW(),NOW()),
(33,5,NOW(),NOW()),(33,7,NOW(),NOW()),(33,16,NOW(),NOW()),
(34,2,NOW(),NOW()),(34,8,NOW(),NOW()),(34,19,NOW(),NOW()),
(35,1,NOW(),NOW()),(35,4,NOW(),NOW()),(35,14,NOW(),NOW()),
(36,3,NOW(),NOW()),(36,6,NOW(),NOW()),(36,9,NOW(),NOW()),
(37,5,NOW(),NOW()),(37,10,NOW(),NOW()),(37,20,NOW(),NOW()),
(38,1,NOW(),NOW()),(38,7,NOW(),NOW()),(38,13,NOW(),NOW()),
(39,2,NOW(),NOW()),(39,8,NOW(),NOW()),(39,15,NOW(),NOW()),
(40,4,NOW(),NOW()),(40,6,NOW(),NOW()),(40,17,NOW(),NOW()),
(41,1,NOW(),NOW()),(41,3,NOW(),NOW()),(41,11,NOW(),NOW()),
(42,5,NOW(),NOW()),(42,9,NOW(),NOW()),(42,18,NOW(),NOW()),
(43,2,NOW(),NOW()),(43,7,NOW(),NOW()),(43,12,NOW(),NOW()),
(44,4,NOW(),NOW()),(44,6,NOW(),NOW()),(44,16,NOW(),NOW()),
(45,1,NOW(),NOW()),(45,8,NOW(),NOW()),(45,20,NOW(),NOW()),
(46,3,NOW(),NOW()),(46,5,NOW(),NOW()),(46,10,NOW(),NOW()),
(47,2,NOW(),NOW()),(47,7,NOW(),NOW()),(47,14,NOW(),NOW()),
(48,1,NOW(),NOW()),(48,4,NOW(),NOW()),(48,19,NOW(),NOW()),
(49,6,NOW(),NOW()),(49,9,NOW(),NOW()),(49,13,NOW(),NOW()),
(50,2,NOW(),NOW()),(50,3,NOW(),NOW()),(50,8,NOW(),NOW()),(50,15,NOW(),NOW());